[project]
name = "notty"
version = "0.3.22"
description = "A simple card game called Notty using Pygame"
authors = [
    {name = "Winipedia"},
    {name = "Azeez"},
    {name = "Hanmiao chen"},
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "platformdirs",
    "pygame",
    "pyrig",
]
classifiers = [
    "Programming Language :: Python :: 3.12",
]
license-files = [
    "LICENSE",
]

[project.scripts]
notty-game = "pyrig.dev.cli.cli:main"
notty = "pyrig.dev.cli.cli:main"

[dependency-groups]
dev = [
    "pyrig-dev",
]

[build-system]
requires = [
    "uv_build",
]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "notty"
module-root = ""

[tool.ruff]
exclude = [
    ".*",
    "**/migrations/*.py",
]

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "D203",
    "D213",
    "COM812",
    "ANN401",
    "S311",
]
fixable = [
    "ALL",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",
]
"**/tests/**/*.py" = [
    "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
strict = true
warn_unreachable = true
show_error_codes = true
files = "."

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--cov=notty --cov-report=term-missing --cov-fail-under=0"

[tool.bandit]
exclude_dirs = [
    ".*",
]
skips = [
    "B311",
]

[tool.bandit.assert_used]
skips = [
    "*/tests/*.py",
    "*test_*.py",
]
