[project]
name = "notty"
version = "0.4.51"
description = "A simple card game called Notty using Pygame"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "platformdirs",
    "pygame",
    "pyrig>=2.2.1",
]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
license-files = [
    "LICENSE",
]
license = "MIT"
keywords = []

[[project.authors]]
name = "Winipedia"
[[project.authors]]
name = "Azeez"
[[project.authors]]
name = "Hanmiao chen"

[[project.maintainers]]
name = "Winipedia"
[project.scripts]
notty-game = "pyrig.rig.cli.cli:main"
notty = "pyrig.rig.cli.cli:main"

[project.urls]
Homepage = "https://github.com/Winipedia/notty"
Documentation = "https://Winipedia.github.io/notty"
Source = "https://github.com/Winipedia/notty"
Issues = "https://github.com/Winipedia/notty/issues"
Changelog = "https://github.com/Winipedia/notty/releases"

[dependency-groups]
dev = [
    "bandit>=1.9.3",
    "mkdocs-material>=9.7.1",
    "mkdocs-mermaid2-plugin>=1.2.3",
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=1.0.3",
    "mypy>=1.19.1",
    "pip-audit>=2.10.0",
    "prek>=0.3.2",
    "pygithub>=2.8.1",
    "pyrig-dev>=0.1.1",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
    "rumdl>=0.1.17",
]

[build-system]
requires = [
    "uv_build",
]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "notty"
module-root = ""

[tool.ruff]
exclude = [
    ".*",
]

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "D203",
    "D213",
    "COM812",
    "ANN401",
]
fixable = [
    "ALL",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--cov=notty --cov-report=term-missing --cov-fail-under=0"

[tool.bandit]
exclude_dirs = [
    ".*",
]

[tool.bandit.assert_used]
skips = [
    "*/tests/*.py",
]

[tool.ty.terminal]
error-on-warning = true

[tool.rumdl]
respect_gitignore = true

[tool.mypy]
strict = true
warn_unreachable = true
show_error_codes = true
files = "."
