[project]
name = "notty"
version = "0.4.13"
description = "A simple card game called Notty using Pygame"
authors = [
    {name = "Winipedia"},
    {name = "Azeez"},
    {name = "Hanmiao chen"},
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "platformdirs>=4.5.1",
    "pygame>=2.6.1",
    "pyrig>=2.2.1",
]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
license-files = [
    "LICENSE",
]
maintainers = [
    {name = "Winipedia"},
]
license = "MIT"
keywords = []

[project.scripts]
notty-game = "pyrig.dev.cli.cli:main"
notty = "pyrig.dev.cli.cli:main"

[project.urls]
Homepage = "https://github.com/Winipedia/notty"
Documentation = "https://Winipedia.github.io/notty"
Source = "https://github.com/Winipedia/notty"
Issues = "https://github.com/Winipedia/notty/issues"
Changelog = "https://github.com/Winipedia/notty/releases"

[dependency-groups]
dev = [
    "pyrig-dev>=0.1.1",
]

[build-system]
requires = [
    "uv_build",
]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "notty"
module-root = ""

[tool.ruff]
exclude = [
    ".*",
    "**/migrations/*.py",
]

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "D203",
    "D213",
    "COM812",
    "ANN401",
]
fixable = [
    "ALL",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
strict = true
warn_unreachable = true
show_error_codes = true
files = "."

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--cov=notty --cov-report=term-missing --cov-fail-under=0"

[tool.bandit]
exclude_dirs = [
    ".*",
]

[tool.bandit.assert_used]
skips = [
    "*/tests/*.py",
]

[tool.ty.terminal]
error-on-warning = true

[tool.rumdl]
respect_gitignore = true
